/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSetoresRouteImport } from './routes/_authenticated/admin.setores'
import { Route as AuthenticatedAdminRespostasRouteImport } from './routes/_authenticated/admin.respostas'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin.overview'
import { Route as AuthenticatedAdminEtiquetasRouteImport } from './routes/_authenticated/admin.etiquetas'
import { Route as AuthenticatedAdminAgentesRouteImport } from './routes/_authenticated/admin.agentes'
import { Route as AuthenticatedInboxCConversaIdRouteImport } from './routes/_authenticated/inbox.c.$conversaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSetoresRoute =
  AuthenticatedAdminSetoresRouteImport.update({
    id: '/setores',
    path: '/setores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRespostasRoute =
  AuthenticatedAdminRespostasRouteImport.update({
    id: '/respostas',
    path: '/respostas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEtiquetasRoute =
  AuthenticatedAdminEtiquetasRouteImport.update({
    id: '/etiquetas',
    path: '/etiquetas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgentesRoute =
  AuthenticatedAdminAgentesRouteImport.update({
    id: '/agentes',
    path: '/agentes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedInboxCConversaIdRoute =
  AuthenticatedInboxCConversaIdRouteImport.update({
    id: '/c/$conversaId',
    path: '/c/$conversaId',
    getParentRoute: () => AuthenticatedInboxRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/admin/agentes': typeof AuthenticatedAdminAgentesRoute
  '/admin/etiquetas': typeof AuthenticatedAdminEtiquetasRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/respostas': typeof AuthenticatedAdminRespostasRoute
  '/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/inbox/c/$conversaId': typeof AuthenticatedInboxCConversaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/agentes': typeof AuthenticatedAdminAgentesRoute
  '/admin/etiquetas': typeof AuthenticatedAdminEtiquetasRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/respostas': typeof AuthenticatedAdminRespostasRoute
  '/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/inbox/c/$conversaId': typeof AuthenticatedInboxCConversaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/admin/agentes': typeof AuthenticatedAdminAgentesRoute
  '/_authenticated/admin/etiquetas': typeof AuthenticatedAdminEtiquetasRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin/respostas': typeof AuthenticatedAdminRespostasRoute
  '/_authenticated/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/inbox/c/$conversaId': typeof AuthenticatedInboxCConversaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/inbox'
    | '/admin/agentes'
    | '/admin/etiquetas'
    | '/admin/overview'
    | '/admin/respostas'
    | '/admin/setores'
    | '/admin/'
    | '/inbox/'
    | '/inbox/c/$conversaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/agentes'
    | '/admin/etiquetas'
    | '/admin/overview'
    | '/admin/respostas'
    | '/admin/setores'
    | '/admin'
    | '/inbox'
    | '/inbox/c/$conversaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/inbox'
    | '/_authenticated/admin/agentes'
    | '/_authenticated/admin/etiquetas'
    | '/_authenticated/admin/overview'
    | '/_authenticated/admin/respostas'
    | '/_authenticated/admin/setores'
    | '/_authenticated/admin/'
    | '/_authenticated/inbox/'
    | '/_authenticated/inbox/c/$conversaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setores': {
      id: '/_authenticated/admin/setores'
      path: '/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AuthenticatedAdminSetoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/respostas': {
      id: '/_authenticated/admin/respostas'
      path: '/respostas'
      fullPath: '/admin/respostas'
      preLoaderRoute: typeof AuthenticatedAdminRespostasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/etiquetas': {
      id: '/_authenticated/admin/etiquetas'
      path: '/etiquetas'
      fullPath: '/admin/etiquetas'
      preLoaderRoute: typeof AuthenticatedAdminEtiquetasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agentes': {
      id: '/_authenticated/admin/agentes'
      path: '/agentes'
      fullPath: '/admin/agentes'
      preLoaderRoute: typeof AuthenticatedAdminAgentesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/inbox/c/$conversaId': {
      id: '/_authenticated/inbox/c/$conversaId'
      path: '/c/$conversaId'
      fullPath: '/inbox/c/$conversaId'
      preLoaderRoute: typeof AuthenticatedInboxCConversaIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgentesRoute: typeof AuthenticatedAdminAgentesRoute
  AuthenticatedAdminEtiquetasRoute: typeof AuthenticatedAdminEtiquetasRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminRespostasRoute: typeof AuthenticatedAdminRespostasRoute
  AuthenticatedAdminSetoresRoute: typeof AuthenticatedAdminSetoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgentesRoute: AuthenticatedAdminAgentesRoute,
  AuthenticatedAdminEtiquetasRoute: AuthenticatedAdminEtiquetasRoute,
  AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
  AuthenticatedAdminRespostasRoute: AuthenticatedAdminRespostasRoute,
  AuthenticatedAdminSetoresRoute: AuthenticatedAdminSetoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
  AuthenticatedInboxCConversaIdRoute: typeof AuthenticatedInboxCConversaIdRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  AuthenticatedInboxCConversaIdRoute: AuthenticatedInboxCConversaIdRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
